name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Debug: list everything in the runner
      - name: 📂 List workspace files
        run: |
          echo "Working dir: $(pwd)"
          ls -R .

      # 3) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4) Build & push server image
      - name: Build & Push Server Image
        uses: docker/build-push-action@v3
        with:
          context: ./serverSideApp
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/server-app:latest

      # 5) Build & push client image
      - name: Build & Push Client Image
        uses: docker/build-push-action@v3
        with:
          context: ./clientSideApp
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/client-app:latest

      # 6) Deploy via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            cd /home/ubuntu/DiceCampProject
            git pull origin main
            chmod +x deploy.sh
            ./deploy.sh
