name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Debug: ensure DOCKER_USERNAME is available (won't fail)
      - name: Debug DOCKER_USERNAME
        run: |
          echo "DOCKER_USERNAME = '${{ secrets.DOCKER_USERNAME }}'"
          echo "Any DOCKER_* env vars:"
          env | grep DOCKER || echo "(none)"

      # 3) List files so we can confirm build contexts exist
      - name: List workspace files
        run: |
          echo "Working directory: $(pwd)"
          ls -R .

      # 4) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5) Build & push server image
      - name: Build & Push Server Image
        uses: docker/build-push-action@v3
        with:
          context: ./serverSideApp
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/server-app:latest

      # 6) Build & push client image
      - name: Build & Push Client Image
        uses: docker/build-push-action@v3
        with:
          context: ./clientSideApp
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/client-app:latest

      # 7) Deploy to EC2 via SSH
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            cd /home/ubuntu/DiceCampProject
            git pull origin main
            chmod +x deploy.sh
            ./deploy.sh
