name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- DEBUG: confirm directory structure ---
      - name: List workspace files
        run: |
          echo "Working directory: $(pwd)"
          ls -R .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Server Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/server-app:latest ./serverSideApp
          docker push ${{ secrets.DOCKER_USERNAME }}/server-app:latest

      - name: Build and Push Client Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/client-app:latest ./clientSideApp
          docker push ${{ secrets.DOCKER_USERNAME }}/client-app:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # make Docker username available inside deploy.sh
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            cd /home/ubuntu/DiceCampProject
            git pull origin main
            chmod +x deploy.sh
            ./deploy.sh
