name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3) Build and push the server Docker image
      - name: Build & Push Server Image
        uses: docker/build-push-action@v3
        with:
          context: ./serverSideApp
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/server-app:latest

      # 4) Build and push the client Docker image
      - name: Build & Push Client Image
        uses: docker/build-push-action@v3
        with:
          context: ./clientSideApp
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/client-app:latest

      # 5) Deploy to EC2 using SSH
            - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "✅ Logged in to EC2"
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            echo "DOCKER_USERNAME in EC2 = $DOCKER_USERNAME"
            cd /home/ubuntu/DiceCampProject
            git reset --hard HEAD
            git pull origin main
            chmod +x deploy.sh
            ./deploy.sh
